site_name: Documentation tutorials
site_description: "Example documented repo"
site_url: "https://equalapriori.github.io/..."
repo_url: "https://github.com/EqualAPriori/..."
repo_name: "..."
site_dir: "site"

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.top 
  - navigation.sections
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - toc:
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
# Other potential extensions:
# - data
# - latex
# - many more: https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



plugins:
  - mkdocs-jupyter
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
          - import sys
          - sys.path.append("docs")
          selection:
            new_path_syntax: yes
          rendering:
            show_source: true
      watch:
        - src/

nav:
    - "Home": index.md
    - "markdown": markdown.md
    - "docstrings": docstrings.md
    - "pdoc3": pdoc3.md
    - "mkdocs": mkdocs.md
    - "Reference": 
        - "At a glance": reference/ToC.md
        - "Src": reference/

