site_name: __CUSTOMSITENAME__
site_description: "Example documented repo"
site_url: "https://equalapriori.github.io/..."
repo_url: "https://github.com/EqualAPriori/..."
repo_name: "..."
site_dir: "site"

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
  #name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - toc:
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - attr_list
# Other potential extensions:
# - many more: https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists

plugins:
  - mkdocs-jupyter
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
          - import sys
          - sys.path.append("docs")
          selection:
            new_path_syntax: yes
          rendering:
            show_source: true
      watch:
        - src/__MYPACKAGE__

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
    - "Home": index.md
    - "Reference": 
        - "At a glance": reference/ToC.md
        - "Src": reference/

